// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaskBoard.Api.Data;

#nullable disable

namespace TaskBoard.Api.Migrations
{
    [DbContext(typeof(TaskBoardDbContext))]
    [Migration("20260315000000_AddLastStatusNoteToTicket")]
    partial class AddLastStatusNoteToTicket
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("TaskBoard.Api.Data.AttachmentEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("ContentType")
                        .HasColumnType("TEXT")
                        .HasColumnName("content_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<long>("Size")
                        .HasColumnType("INTEGER")
                        .HasColumnName("size");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("storage_path");

                    b.Property<string>("TicketId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("ticket_id");

                    b.HasKey("Id");

                    b.HasIndex("TicketId");

                    b.ToTable("attachments", (string)null);
                });

            modelBuilder.Entity("TaskBoard.Api.Data.CounterEntity", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT")
                        .HasColumnName("key");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("value");

                    b.HasKey("Key");

                    b.ToTable("counters", (string)null);
                });

            modelBuilder.Entity("TaskBoard.Api.Data.DependencyEntity", b =>
                {
                    b.Property<string>("TicketId")
                        .HasColumnType("TEXT")
                        .HasColumnName("ticket_id");

                    b.Property<string>("BlockedById")
                        .HasColumnType("TEXT")
                        .HasColumnName("blocked_by_id");

                    b.HasKey("TicketId", "BlockedById");

                    b.HasIndex("BlockedById");

                    b.ToTable("deps", (string)null);
                });

            modelBuilder.Entity("TaskBoard.Api.Data.EventEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("payload_json");

                    b.Property<string>("TicketId")
                        .HasColumnType("TEXT")
                        .HasColumnName("ticket_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("TicketId", "CreatedAt");

                    b.HasIndex("Type", "CreatedAt");

                    b.ToTable("events", (string)null);
                });

            modelBuilder.Entity("TaskBoard.Api.Data.RunEntity", b =>
                {
                    b.Property<string>("TicketId")
                        .HasColumnType("TEXT")
                        .HasColumnName("ticket_id");

                    b.Property<int>("Attempt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("attempt");

                    b.Property<string>("Branch")
                        .HasColumnType("TEXT")
                        .HasColumnName("branch");

                    b.Property<string>("LastCiState")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("last_ci_state");

                    b.Property<string>("LastError")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_error");

                    b.Property<string>("LastSummary")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_summary");

                    b.Property<DateTime?>("LockExpiresAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("lock_expires_at");

                    b.Property<string>("LockOwner")
                        .HasColumnType("TEXT")
                        .HasColumnName("lock_owner");

                    b.Property<string>("PendingApprovalDecisionId")
                        .HasColumnType("TEXT")
                        .HasColumnName("pending_approval_decision_id");

                    b.Property<string>("Phase")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("phase");

                    b.Property<int?>("PrNumber")
                        .HasColumnType("INTEGER")
                        .HasColumnName("pr_number");

                    b.Property<string>("PrUrl")
                        .HasColumnType("TEXT")
                        .HasColumnName("pr_url");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<string>("WorkflowId")
                        .HasColumnType("TEXT")
                        .HasColumnName("workflow_id");

                    b.HasKey("TicketId");

                    b.HasIndex("LockExpiresAt");

                    b.ToTable("runs", (string)null);
                });

            modelBuilder.Entity("TaskBoard.Api.Data.TicketEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("AcceptanceCriteriaJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("acceptance_criteria_json");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_deleted");

                    b.Property<string>("LabelsJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("labels_json");

                    b.Property<string>("LastStatusNote")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_status_note");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER")
                        .HasColumnName("priority");

                    b.Property<string>("Repo")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("repo");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<string>("TestPlan")
                        .HasColumnType("TEXT")
                        .HasColumnName("test_plan");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("Status", "Repo", "UpdatedAt");

                    b.ToTable("tickets", (string)null);
                });

            modelBuilder.Entity("TaskBoard.Api.Data.AttachmentEntity", b =>
                {
                    b.HasOne("TaskBoard.Api.Data.TicketEntity", "Ticket")
                        .WithMany("Attachments")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("TaskBoard.Api.Data.DependencyEntity", b =>
                {
                    b.HasOne("TaskBoard.Api.Data.TicketEntity", "BlockedBy")
                        .WithMany("Blocks")
                        .HasForeignKey("BlockedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TaskBoard.Api.Data.TicketEntity", "Ticket")
                        .WithMany("BlockedBy")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BlockedBy");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("TaskBoard.Api.Data.EventEntity", b =>
                {
                    b.HasOne("TaskBoard.Api.Data.TicketEntity", "Ticket")
                        .WithMany("Events")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("TaskBoard.Api.Data.RunEntity", b =>
                {
                    b.HasOne("TaskBoard.Api.Data.TicketEntity", "Ticket")
                        .WithOne("Run")
                        .HasForeignKey("TaskBoard.Api.Data.RunEntity", "TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("TaskBoard.Api.Data.TicketEntity", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("BlockedBy");

                    b.Navigation("Blocks");

                    b.Navigation("Events");

                    b.Navigation("Run");
                });
#pragma warning restore 612, 618
        }
    }
}
